
@baseUrl = https://localhost:44310/api
@contentType = application/json

###
# Login by username and password
# @name login

POST {{baseUrl}}/User/Login HTTP/1.1
Content-Type: {{contentType}}

{
  "userName": "admin",
  "password": "123"
}

###
# Auth token
@authToken = {{login.response.body.$.token}}

###
# Information about current user
GET {{baseUrl}}/User/GetCurrentUser HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

###
# Information about API user
GET {{baseUrl}}/User/GetIdentityUser HTTP/1.1
Content-Type: {{contentType}}
X-API-KEY: API-KEY-123

###
# Get weather forecast, Bearer authorization
GET {{baseUrl}}/WeatherForecast HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

###
# Get weather forecast, NO authorization
GET {{baseUrl}}/WeatherForecast HTTP/1.1
Content-Type: {{contentType}}

###
# Get weather forecast, API key authorization
GET {{baseUrl}}/WeatherForecast HTTP/1.1
Content-Type: {{contentType}}
X-API-KEY: API-KEY-123

###
# Get weather forecast, wrong API key authorization
GET {{baseUrl}}/WeatherForecast HTTP/1.1
Content-Type: {{contentType}}
X-API-KEY: WRONG-KEY

